#! /bin/bash
aws --profile rudenos s3 sync ./ s3://www.hughesindustries.uk/ --exclude ".git/*" --exclude ".git*" --exclude "s3/*" --acl public-read
aws --profile rudenos s3 sync ./ s3://www.hughes.industries/ --exclude ".git/*" --exclude ".git*" --exclude "s3/*" --acl public-read
